# Generated by Django 3.1.7 on 2021-11-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('user', models.CharField(max_length=200)),
                ('comment', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_id', models.CharField(max_length=10)),
                ('comment_user', models.CharField(max_length=100)),
                ('user_comments', models.TextField()),
                ('comment_date', models.DateTimeField()),
                ('comment_likes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='editpages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=250)),
                ('page_content', models.TextField()),
                ('mtitle', models.TextField()),
                ('mkeywords', models.TextField()),
                ('mdescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='joinus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('profile_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('quotation', models.TextField()),
                ('arrival_date', models.CharField(max_length=100)),
                ('departure_date', models.CharField(max_length=100)),
                ('cause_death', models.TextField()),
                ('place_death', models.CharField(max_length=250)),
                ('other', models.TextField()),
                ('rest_place', models.CharField(max_length=200)),
                ('other_names', models.TextField()),
                ('ethnicity', models.CharField(max_length=200)),
                ('alma', models.TextField()),
                ('political', models.TextField()),
                ('religion', models.CharField(max_length=200)),
                ('spouse', models.CharField(max_length=200)),
                ('children', models.TextField()),
                ('parents', models.TextField()),
                ('known', models.TextField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=60)),
                ('Lname', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=60)),
                ('Phone', models.CharField(max_length=60)),
                ('Fax', models.CharField(max_length=60)),
                ('Password', models.CharField(max_length=60)),
                ('Status', models.SmallIntegerField(default=0)),
                ('created_date', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.IntegerField()),
                ('placed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_surname', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=100)),
                ('user_status', models.IntegerField()),
                ('user_created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('video_title', models.CharField(max_length=250)),
                ('video_poster', models.CharField(max_length=200)),
                ('video_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('visit', models.DateTimeField()),
                ('ip', models.CharField(max_length=20)),
            ],
        ),
    ]
